version: '3.9'
services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - '8069:8069'
      - '8072:8072'  # Añadido para websocket
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config_odoo:/etc/odoo
      - ./dev_addons:/mnt/extra-addons
      - ./log:/var/log/odoo
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=myodoo
      - TZ=America/La_Paz  # Añadida zona horaria de Bolivia
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2'
        reservations:
          memory: 2G
    restart: unless-stopped

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
      - TZ=America/La_Paz  # Añadida zona horaria de Bolivia
    ports:
      - "5445:5432" 
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
    restart: unless-stopped

volumes:
  odoo-web-data:
  odoo-db-data: